config/routes.rb
Rails.application.routes.draw do

  resources :home, only: :index

  resources :incomes, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks}

  resources :expenses

  root controller: :home, action: :index

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
end

app/models/income.rb
class Income < ApplicationRecord
  validates :amount, presence: true

  belongs_to :user
end

app/models/saving_goal.rb
class SavingGoal < ApplicationRecord
  validates :amount, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.user = current_user
    if @expense.save
      flash[:success] = "Expense saved!"
      render 'home/index'
    else
      flash[:error] = "Please enter valid amount"
      render 'new'
    end
  end


  private

  def expense_params
    params.require(:expense).permit(:rent, :insurance, :transportation,
       :education, :food, :leisure_activities, :cultural_activities,
       :holidays, :sport, :eating_out, :beauty, :various)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

    def new
    end

    def create
      @income = Income.new(income_params)
      @income.user = current_user
      if @income.save
        flash[:success] = "Income successfully added!"
        render 'home/index'
      else
        flash[:error] = "Please enter valid amount"
        render 'new'
      end
    end

    private

    def income_params
      params.require(:income).permit(:amount)
    end


end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path, notice: 'That did not work!'
  end
end

app/controllers/saving_goals_controller.rb
class SavingGoalsController < ApplicationController
  def new
  end

  def create
    binding.pry
    @saving_goal = SavingGoal.new(saving_goal_params.merge(user: current_user))
    if @saving_goal.save
      flash[:success] = "Savings Goal saved"
      render 'home/index'
    else
      flash[:error] = "Please enter valid amount"
      render 'new'
    end
  end


  private

  def saving_goal_params
    params.require(:saving_goal).permit(:amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/new.html.erb
<h1>YOUR EXPENSES</h1>
<h2>How do you spend your income?<br />Let's find it out!</h2><br />
<h3>Please enter your montlhy fixed expenses:</h3>
<%= form_with model: Expense.new do |form| %>
  <!-- <%= "Enter Fixed Expenses" %> -->
  <%= form.text_field :rent, placeholder: "Rent" %>
  <%= form.text_field :insurance, placeholder: "Insurance" %><br />
  <%= form.text_field :transportation, placeholder: "Transportation" %>
  <%= form.text_field :education, placeholder: "Education" %><br />
  <%= form.text_field :food, placeholder: "Food" %>
  <%= form.text_field :other, placeholder: "Other" %><br />

  <h3>And now your leisure expenses:</h3>
  <%= form.text_field :leisure_activities, placeholder: "Leisure activities" %>
  <%= form.text_field :cultural_activities, placeholder: "Cultural activities" %><br />
  <%= form.text_field :holidays, placeholder: "Holidays" %>
  <%= form.text_field :sport, placeholder: "Sport" %><br />
  <%= form.text_field :eating_out, placeholder: "Eating out" %>
  <%= form.text_field :beauty, placeholder: "Beauty" %><br />
  <%= form.text_field :various, placeholder: "Various" %><br />
  <p><%= form.submit ("Submit")%></p>
<% end %>

app/views/fixed_costs/new.html.erb
<%= form_with model: FixedCost.new do |form| %>
  <%= "Enter Fixed Expenses" %>
  <%= form.text_field :rent, placeholder: "Rent" %>
  <%= form.text_field :insurance, placeholder: "Insurance" %>
  <%= form.text_field :transportation, placeholder: "Transportation" %>
  <%= form.text_field :education, placeholder: "Education" %>
  <%= form.text_field :food, placeholder: "Food" %>
  <%= form.text_field :other, placeholder: "Other" %>
  <%= form.submit ("Submit")%>
<% end %>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Welcome to BrokeNoMore!</h1>
  <p class="lead">BREAK FREE FROM YOUR EXPENSES</p>
  <hr class="my-4">
  <p>BrokeNoMore is a free budget manager.</p>
  <p>We bring together all of your expenses and show you how you can save money for your next project.</p>
  <p class="lead"></p>
</div>
<div class="container-fluid">
</div>
<div class="footer">
  <h2>Sign up for BrokeNoMore today</h2><br />
  <p>From budgets and bills, you’ll discover the effortless way to be broke no more.</p><br/>
</div>

app/views/home/show.html.erb
<%= form_with model: @income do |form| %>
  <%= "Enter Monthly Income" %>
  <%= form.number_field :amount, :placeholder => "Fill here" %>
  <%= form.submit ("Submit")%>
<% end %>

app/views/income/new.html.erb
<%= form_with model: Income.new, url: income_index_path do |form| %>
  <%= "Enter Monthly Income" %>
  <%= form.number_field :amount, :placeholder => "Fill here" %>
  <%= form.submit ("Submit")%>
<% end %>

app/views/incomes/new.html.erb
<h1>YOUR INCOMES</h1>
<h2>What is your monthly income?</h2>
<%= form_with model: Income.new do |form| %>
  <%= 'Enter Monthly Income' %>
  <%= form.number_field :amount, placeholder: 'Fill here' %><br />
<p><%= form.submit ('Submit')%></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div class="nav_title">
    <%= link_to 'BrokeNoMore', root_path, :class => 'nav-item nav-link active' %>
    <% if user_signed_in? %>
      <p>Logged in as <strong><%= current_user.email %></strong></p>
    <% end %>
  </div>
  <div class="navbar-nav mr-sm-2">
    <% if user_signed_in? %>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-item nav-link' %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-item nav-link' %>
      <%= link_to "New Income", new_income_path, :class => 'nav-item nav-link' %>
      <%= link_to "New Expense", new_expense_path, :class => 'nav-item nav-link' %>
    <% else %>
      <%= link_to "Register", new_user_registration_path, :class => 'nav-item nav-link' %>
      <%= link_to "Login", new_user_session_path, :class => 'nav-item nav-link' %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrokeNoMore</title>
    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great|Palanquin" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'CA Mailboxer', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_up? %>
          <li><%= link_to "Hello, #{current_user.name}", "#" %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="active"><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/saving_goals/new.html.erb
<%= form_with model: SavingGoal.new do |form| %>
  <%= 'Enter Savings Goal' %>
  <%= form.number_field :saving_goal, placeholder: 'Fill here' %>
  <%= form.submit ('Submit')%>
<% end %>